// Code generated by Kitex v0.14.1. DO NOT EDIT.

package chat

import (
	"context"

	"github.com/cloudwego/prutal"
)

type ChatReq struct {
	UserInput string `protobuf:"bytes,1,opt,name=user_input" json:"user_input,omitempty"`
}

func (x *ChatReq) Reset() { *x = ChatReq{} }

func (x *ChatReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatReq) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

type ChatResp struct {
	Answer string `protobuf:"bytes,1,opt,name=answer" json:"answer,omitempty"`
}

func (x *ChatResp) Reset() { *x = ChatResp{} }

func (x *ChatResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type ChatService interface {
	Chat(ctx context.Context, req *ChatReq) (res *ChatResp, err error)
}
